# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_DPTX_DRIVER) += dptx_aux_helper.o
obj-$(CONFIG_AMLOGIC_DPTX_DRIVER) += dptx_check_valid.o
obj-$(CONFIG_AMLOGIC_DPTX_DRIVER) += dptx_common.o
obj-$(CONFIG_AMLOGIC_DPTX_DRIVER) += dptx_drv.o
obj-$(CONFIG_AMLOGIC_DPTX_DRIVER) += dptx_hw_common.o
obj-$(CONFIG_AMLOGIC_DPTX_DRIVER) += dptx_infoframe.o
obj-$(CONFIG_AMLOGIC_DPTX_DRIVER) += dptx_link.o
obj-$(CONFIG_AMLOGIC_DPTX_DRIVER) += dptx_timer.o
obj-$(CONFIG_AMLOGIC_DPTX_DRIVER) += dptx_log.o
obj-$(CONFIG_AMLOGIC_DPTX_DRIVER) += dptx_sysfs.o
obj-$(CONFIG_AMLOGIC_DPTX_DRIVER) += dptx_vout.o
obj-$(CONFIG_AMLOGIC_DPTX_DRIVER) += edptx_core_api.o

obj-$(CONFIG_AMLOGIC_DPTX) += dp20/
