# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

obj-$(CONFIG_AMLOGIC_DPTX) += dptx_hw_aux.o
obj-$(CONFIG_AMLOGIC_DPTX) += dptx_hw.o
obj-$(CONFIG_AMLOGIC_DPTX) += dptx_pktmgmt.o
obj-$(CONFIG_AMLOGIC_DPTX) += dptx_hw_timer.o
obj-$(CONFIG_AMLOGIC_DPTX) += dptx_reg.o
