// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (c) 2019 Amlogic, Inc. All rights reserved.
 */

char *domain_name[] = {
    "PDID_USB2",
    "PDID_USB3",
    "PDID_DOS_HCODEC",
    "PDID_DOS_HEVC",
    "PDID_TAHOE",
    "PDID_VPU_VOUT",
    "PDID_SD_EMMC_A",
    "PDID_SD_EMMC_B",
    "PDID_SD_EMMC_C",
    "PDID_ETH",
    "PDID_NNA3",
    "PDID_NNA2",
    "PDID_AMFC",
    "PDID_ISP",
    "PDID_GE2D",
    "PDID_CVE",
    "PDID_DEWARP",
    "PDID_AI_ISP",
    "PDID_DSI",
    "PDID_PCIE",
    "PDID_U3P2_COMP",
    "PDID_AO_SED",
    "PDID_AO_ISP",
    "PDID_AO_SPI",
    "PDID_AO_UART_A",
    "PDID_AO_UART_B",
    "PDID_AO_SPISG",
    "PDID_AO_I2C_A",
    "PDID_AO_I2C_B",
    "PDID_AO_I3C",
    "PDID_AO_IR",
    "PDID_AO_PWM_A",
    "PDID_AO_PWM_B",
    "PDID_AO_PSRAM",
    "PDID_AUDIO_TOP",
    "PDID_CAN0",
    "PDID_CAN1",
};
