# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_PINCTRL_MESON_T6D)		+= pinctrl-meson-t6d.o
obj-$(CONFIG_PINCTRL_MESON_T6W)		+= pinctrl-meson-t6w.o
obj-$(CONFIG_PINCTRL_MESON_S7)		+= pinctrl-meson-s7.o
obj-$(CONFIG_PINCTRL_MESON_X1)		+= pinctrl-meson-x1.o
obj-$(CONFIG_PINCTRL_MESON_C4)		+= pinctrl-meson-c4.o
obj-$(CONFIG_PINCTRL_MESON_A9)		+= pinctrl-meson-a9.o
obj-$(CONFIG_PINCTRL_MESON_C5)		+= pinctrl-meson-c5.o
