# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

#obj-$(CONFIG_AMLOGIC_TX_CONNECTOR_COMMON_MODERN) += meson_tx_task_mgr_linux.o \
#obj-$(CONFIG_AMLOGIC_TX_CONNECTOR_COMMON_MODERN) += meson_tx_vout.o \
#obj-$(CONFIG_AMLOGIC_TX_CONNECTOR_COMMON_MODERN) += meson_tx_event_mgr.o \
#obj-$(CONFIG_AMLOGIC_DPTX) += phy/meson_tx_phy_core.o
#obj-$(CONFIG_AMLOGIC_DPTX) += phy/meson_tx_phy_drv.o
#obj-$(CONFIG_AMLOGIC_DPTX) += phy/meson_tx_dummy_phy_drv.o
#obj-$(CONFIG_AMLOGIC_DPTX) += clk/meson_tx_clk.o
#obj-$(CONFIG_AMLOGIC_DPTX) += clk/tx_clk_a9.o

obj-$(CONFIG_AMLOGIC_DPTX) += cea861.o
obj-$(CONFIG_AMLOGIC_DPTX) += meson_tx_dev.o
obj-$(CONFIG_AMLOGIC_DPTX) += meson_tx_log.o
obj-$(CONFIG_AMLOGIC_DPTX) += meson_tx_hw.o
obj-$(CONFIG_AMLOGIC_DPTX) += meson_tx_edid_parse.o
obj-$(CONFIG_AMLOGIC_DPTX) += meson_tx_mode.o
obj-$(CONFIG_AMLOGIC_DPTX) += venc/meson_venc.o
obj-$(CONFIG_AMLOGIC_DPTX) += phy/meson_tx_phy_core.o
obj-$(CONFIG_AMLOGIC_DPTX) += phy/meson_tx_phy_drv.o
obj-$(CONFIG_AMLOGIC_DPTX) += phy/meson_tx_dummy_phy_drv.o
obj-$(CONFIG_AMLOGIC_DPTX) += clk/meson_tx_clk.o
obj-$(CONFIG_AMLOGIC_DPTX) += clk/tx_clk_a9.o
#include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/meson_tx_connector/hdmitx/Makefile
#include $(srctree)/$(COMMON_DRIVERS_DIR)/drivers/media/vout/meson_tx_connector/hdcp/Makefile
obj-$(CONFIG_AMLOGIC_DPTX) += dptx/
