
obj-$(CONFIG_AML_LCD_MIPI_DSI) += MIPI_DSI/
obj-$(CONFIG_AML_LCD_TCON)     += tcon/
obj-$(CONFIG_AML_LCD_VBYONE)   += vbyone.o

obj-$(CONFIG_AML_LCD) += DPI.o
obj-$(CONFIG_AML_LCD) += lvds.o
obj-$(CONFIG_AML_LCD) += lcd_connector_common.o
