obj-$(CONFIG_AML_LCD) += lcd_phy_if.o
obj-$(CONFIG_AML_LCD) += lcd_phy_utils.o
obj-$(CONFIG_AML_LCD) += lcd_phy_s6.o
obj-$(CONFIG_AML_LCD) += lcd_phy_t3x.o
obj-$(CONFIG_AML_LCD) += lcd_phy_t6d.o
obj-$(CONFIG_AML_LCD) += lcd_phy_a9.o
