# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_AML_CVBS) += cvbs/

obj-$(CONFIG_AML_LCD) += lcd/

obj-$(CONFIG_AML_eDPTX) += eDPTX/

obj-$(CONFIG_AML_VOUT) += vout.o

obj-$(CONFIG_AML_HDMITX) += hdmitx/

obj-$(CONFIG_AMLOGIC_DPTX) += meson_tx_connector/
