
obj-$(CONFIG_AML_eDPTX) += VENC/
obj-$(CONFIG_AML_eDPTX) += CLK/
obj-$(CONFIG_AML_eDPTX) += PHY/
obj-$(CONFIG_AML_eDPTX) += eDP_IP/

obj-$(CONFIG_AML_eDPTX) += eDP_vout.o
obj-$(CONFIG_AML_eDPTX) += eDP_common.o

obj-$(CONFIG_AML_eDPTX) += eDP_DACP.o
obj-$(CONFIG_AML_eDPTX) += eDP_debug.o
obj-$(CONFIG_AML_eDPTX) += eDP_drv.o
obj-$(CONFIG_AML_eDPTX) += eDP_EDID_DisplayID.o
obj-$(CONFIG_AML_eDPTX) += eDP_GPIO_ctrl.o
obj-$(CONFIG_AML_eDPTX) += eDP_link_training.o
obj-$(CONFIG_AML_eDPTX) += eDP_vmode_mgr.o
obj-$(CONFIG_AML_eDPTX) += eDP_utils.o