# SPDX-License-Identifier: GPL-2.0
#
obj-y += clk.o
obj-$(CONFIG_CLK_MESON_T6D) += clk_meson_t6d.o clk_measure.o
obj-$(CONFIG_CLK_MESON_T6W) += clk_meson_t6w.o clk_measure.o
obj-$(CONFIG_CLK_MESON_S7) += clk_meson_s7.o clk_measure.o clk-pll.o
obj-$(CONFIG_CLK_MESON_X1) += clk_meson_x1.o clk_measure.o
obj-$(CONFIG_CLK_MESON_C4) += clk_meson_c4.o clk_measure.o clk-pll.o clk-core.o
obj-$(CONFIG_CLK_MESON_A9) += clk_meson_a9.o clk_measure.o clk-pll.o clk-core.o
obj-$(CONFIG_CLK_MESON_C5) += clk_meson_c5.o clk_measure.o clk-pll.o clk-core.o
