
obj-$(CONFIG_AML_LCD_TCON) += lcd_tcon.o
obj-$(CONFIG_AML_LCD_TCON) += lcd_tcon_hw.o
obj-$(CONFIG_AML_LCD_TCON) += lcd_tcon_spi.o
obj-$(CONFIG_AML_LCD_TCON) += lcd_tcon_debug.o
obj-$(CONFIG_AML_LCD_TCON) += lcd_tcon_dccd.o
